backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  -
    name: "post"
    label: "Posts"
    label_singular: "Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Description(optimally 150 characters)", name: "description", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Twitter card type(summary by default)", name: "twitter-card", widget: "string", required: false}
      - {label: "Date posted", name: "date", format: "YYYY-MM-DD hh:mm:ss +0200", widget: "datetime"}
      - {label: "Category(with spaces)", name: "category", widget: "string"}
      - {label: "Author name(name and surname, with spaces)", name: "author", widget: "string"}
      - {label: "Author avatar(optimally 100x100px)", name: "avatar", widget: "image"}
      - {label: "Post image(optimally 800x313px)", name: "image", widget: "image"}
      - {label: "Post preview(160 to 360 characters)", name: "text-preview", widget: "text"}
      - label: "Tags(with spaces and separated by commas, ex: 'React Js Development, Ruby on Rails development')"
        name: "tags"
        widget: "list"
        allow_add: true
      - {label: "Body", name: "body", widget: "markdown"}
  -
    name: "career"
    label: "Job offers"
    label_singular: "Job offer"
    folder: "_career"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Description(optimally 150 characters)", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "career-details"}
      - {label: "Meta Image", name: "image", widget: "image", required: false}
      - {label: "Twitter card type(summary by default)", name: "twitter-card", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Who we are", name: "who_we_are", widget: "text"}
      - label: "Offer type"
        name: "type"
        widget: "select"
        options: ["Development", "UX/UI", "Sales&Marketing", "Business Development", "Operations", "Other"]
      - {label: "Salary", name: "salary", widget: "string", default: "salary from XXXX pln net"}
      - label: "Responsibilities"
        name: "responsibilities"
        widget: "list"
        allow_add: true
        required: false
      - label: "Requirements"
        name: "requirements"
        widget: "list"
        allow_add: true
        required: false
      - label: "Nicehave"
        name: "nicehave"
        widget: "list"
        allow_add: true
        required: false
      - label: "Offer"
        name: "offer"
        widget: "list"
        allow_add: true
        required: false
      - label: "Salary range"
        name: "salary-range"
        widget: "list"
        allow_add: true
        required: false
  -
    name: "portfolio"
    label: "Portfolio"
    folder: "_portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio-details"}
      - {label: "Meta image(optimally 800x313px)", name: "image", widget: "image"}
      - {label: "Twitter card type(summary by default)", name: "twitter-card", widget: "string", required: false}
      - {label: "Project font colour(if necessary)", name: "project-font-colour", widget: "string", required: false}
      - {label: "Project screenshot", name: "project-screenshot", widget: "image"}
      - {label: "Project logo(max 50px height)", name: "project-logo", widget: "image"}
      - {label: "Project logo class(if necessary)", name: "project-logo-class", widget: "string", required: false}
      - {label: "Banner background image", name: "banner-bg", widget: "image"}
      - {label: "Banner text(not more than 300 characters)", name: "banner-text", widget: "string"}
      - {label: "Banner technologies(3 to 5 separated by commas)", name: "banner-tech", widget: "string"}
      - {label: "The need title(50 characters max)", name: "step-one-title", widget: "string"}
      - {label: "The need description", name: "step-one-text", widget: "markdown"}
      - {label: "The need image", name: "step-one-image", widget: "image", required: false}
      - {label: "The solution title(50 characters max)", name: "step-two-title", widget: "string"}
      - {label: "The solution description", name: "step-two-text", widget: "markdown"}
      - {label: "The solution image", name: "step-two-image", widget: "image", required: false}
      - {label: "The tools title(50 characters max)", name: "step-three-title", widget: "string"}
      - {label: "The tools description", name: "step-three-text", widget: "markdown"}
      - {label: "The tools image", name: "step-three-image", widget: "image", required: false}
      - {label: "The tools - development stack technology left", name: "src-stack-1", widget: "image", required: false}
      - {label: "The tools - development stack technology alt left", name: "alt-stack-1", widget: "string", required: false}
      - {label: "The tools - development stack technology center", name: "src-stack-2", widget: "image", required: false}
      - {label: "The tools - development stack technology alt center", name: "alt-stack-2", widget: "string", required: false}
      - {label: "The tools - development stack technology right", name: "src-stack-3", widget: "image", required: false}
      - {label: "The tools - development stack technology alt right", name: "alt-stack-3", widget: "string", required: false}
      - {label: "The results title(50 characters max)", name: "step-four-title", widget: "string"}
      - {label: "The results description", name: "step-four-text", widget: "markdown"}
      - {label: "The results first image", name: "step-four-image-one", widget: "image", required: false}
      - {label: "The results second image", name: "step-four-image-two", widget: "image", required: false}
      - {label: "The results third image", name: "step-four-image-three", widget: "image", required: false}
      - label: "Testimonial"
        name: "testimonial"
        widget: "object"
        required: false
        fields:
          - {label: "Testimonial photo", name: "testimonial-photo", widget: "image", required: false}
          - {label: "Testimonial name", name: "testimonial-name", widget: "string", required: false}
          - {label: "Testimonial brand", name: "testimonial-brand", widget: "string", required: false}
          - {label: "Testimonial logo", name: "testimonial-logo", widget: "image", required: false}
          - {label: "Testimonial statement", name: "testimonial-text", widget: "string", required: false}
      - {label: "Previous case study", name: "slide-left", widget: "string", required: false}
      - {label: "Previous case study image", name: "slide-left-logo", widget: "image", required: false}
      - {label: "Previous case study link", name: "slide-left-link", widget: "string", default: "/project/project_name", required: false}
      - {label: "Next case study", name: "slide-right", widget: "string", required: false}
      - {label: "Next case study image", name: "slide-right-logo", widget: "image", required: false}
      - {label: "Next case study link", name: "slide-right-link", widget: "string", default: "/project/project_name", required: false}
  -
    name: "services"
    label: "Services"
    label_singular: "Services Landing"
    folder: "_services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "description", name: "description", widget: "string"}
      - {label: "Twitter card type(summary by default)", name: "twitter-card", widget: "string", required: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "service"}
      - {label: "permalink", name: "permalink", widget: "string"}
      - {label: "posts-tag", name: "posts-tag", widget: "string"}
      - {label: "heading", name: "heading", widget: "string"}
      - {label: "desc", name: "desc", widget: "string"}
      - {label: "tech-head", name: "tech-head", widget: "string"}
      - {label: "tech-desc-one", name: "tech-desc-one", widget: "string"}
      - {label: "tech-desc-two", name: "tech-desc-two", widget: "string"}
      - {label: "tech-logo-first", name: "tech-logo-first", widget: "image", required: false}
      - {label: "tech-name-first", name: "tech-name-first", widget: "string", required: false}
      - {label: "tech-logo-seconf", name: "tech-logo-second", widget: "image", required: false}
      - {label: "tech-name-second", name: "tech-name-second", widget: "string", required: false}
      - {label: "tech-logo-third", name: "tech-logo-third", widget: "image", required: false}
      - {label: "tech-name-third", name: "tech-name-third", widget: "string", required: false}
      - {label: "advantage-head", name: "advantage-head", widget: "string"}
      - {label: "advantage-subtitle", name: "advantage-subtitle", widget: "string"}
      - {label: "advantage-desc-one-title", name: "advantage-desc-one-title", widget: "string"}
      - {label: "advantage-desc-one", name: "advantage-desc-one", widget: "string"}
      - {label: "advantage-desc-two-title", name: "advantage-desc-two-title", widget: "string"}
      - {label: "advantage-desc-two", name: "advantage-desc-two", widget: "string"}
      - {label: "advantage-desc-three-title", name: "advantage-desc-three-title", widget: "string"}
      - {label: "advantage-desc-three", name: "advantage-desc-three", widget: "string"}
      - {label: "advantage-desc-four-title", name: "advantage-desc-four-title", widget: "string"}
      - {label: "advantage-desc-four", name: "advantage-desc-four", widget: "string"}
      - {label: "projects-slogan", name: "projects-slogan", widget: "string"}
      - {label: "projects-head", name: "projects-head", widget: "string"}
      - label: "Projects"
        name: "projects"
        widget: "list"
        allow_add: true
        fields:
          - label: Project
            name: project
            widget: object
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Desc", name: "desc", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Image", name: "bg", widget: "image"}
              - {label: "Background Image", name: "bg-image", widget: "image"}
      - {label: "blog-head", name: "blog-head", widget: "string"}
      - {label: "blog-desc", name: "blog-desc", widget: "string"}
      - label: "Competences"
        name: "competences"
        widget: "list"
        allow_add: true
        fields:
          - label: Competence
            name: competence
            widget: object
            fields:
              - {label: "Tech image", name: "tech-image", widget: "image"}
              - {label: "Tech name", name: "tech-name", widget: "string"}
              - {label: "Tech link", name: "tech-link", widget: "string"}
      - {label: "competences-text", name: "competences-text", widget: "string"}
